# Cargo.toml (root)
[workspace]
members = [
    "day01", "day02", "day03", "day04", "day05",
    "day06", "day07", "day08", "day09", "day10",
    "day11", "day12", "common"
]

[workspace.dependencies]
itertools = "0.13"
nom = "7.1"
regex = "1.10"
arrayvec = "0.7"
smallvec = "1.13"
